INSERT IGNORE INTO tag (name, category) VALUES
('혼자', 'WITH_WHOM'),
('친구랑', 'WITH_WHOM'),
('연인과', 'WITH_WHOM'),
('가족과', 'WITH_WHOM'),
('동료와', 'WITH_WHOM'),
('반려동물과', 'WITH_WHOM'),

('SNS 갬성샷', 'MOOD'),
('체험·액티비티', 'MOOD'),
('자리잡고 칠링', 'MOOD'),
('유명 관광지', 'MOOD'),
('아웃도어 탐방', 'MOOD'),
('미술관·갤러리', 'MOOD'),
('알고간 블루마크', 'MOOD'),
('익사이팅 활동', 'MOOD'),
('여행지', 'MOOD'),
('쇼핑', 'MOOD'),
('모임장소', 'MOOD'),
('음악', 'MOOD'),
('페스티벌', 'MOOD'),
('독서하면서 편안하게', 'MOOD'),
('모임·목표지', 'MOOD'),
('가성비 굿', 'MOOD');