ALTER TABLE place_log MODIFY COLUMN status ENUM('TEMP', 'PUBLISHED') NOT NULL;
ALTER TABLE tag MODIFY COLUMN category ENUM('WITH_WHOM', 'MOOD') NOT NULL;
ALTER TABLE users MODIFY COLUMN provider ENUM('KAKAO') NOT NULL;
ALTER TABLE users MODIFY COLUMN role ENUM('USER', 'ADMIN') NOT NULL;